### ISSUE TITLE
Budget... maybe qualify the name

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/budget-api#5]
Sorry, this is bikeshedding, but we talk a lot about "budget" on the web... like:
https://timkadlec.com/2014/11/performance-budget-metrics/

And with the Web Payments API starting to ship, there might be some confusion about what this API is about. I've had my head in Web Payments for the last week, so I instantly thought "wait? what? budget for payments?" 🤑 

It might be good to qualify the name somehow.

**Comment by jenharkness** [comment]
When I originally started on an implementation of this, I used BackgroundBudget, but after working with that for a while, it became quite unwieldy, especially since I'd like the API to be flexible for potential non-background uses. I considered a lot of other options, but ended up deciding on budget.

The nice thing about budget is that it’s a general way to describe any accumulating resource which can be used. Although it can be associated with money, it is also commonly associated with resources like processor time or bandwidth.

I also liked it because Mozilla was already using “budget” to describe their internal push limiting mechanism.

**Comment by marcoscaceres** [comment]
Thanks for the clarifications. Closing :)

**Comment by marcoscaceres** [comment]
@jenharkness, I'm trying to find who worked on this on the Mozilla side previously. Any ideas?
